apiVersion: apps/v1
kind: Deployment
metadata:
  name: mybackendlb-deployment
  labels:
    app: my-app
    component: backend

spec:
  template:
    metadata:
      name: mybackendlb-pod
      labels:
        component: backend
        app: my-app
    spec:
      containers:
        - name: mybackendlb-container
          image: pskrzypk/mybackendlb
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: myapp-secret
                  key: PGPASSWORD
            - name: PGDATABASE
              valueFrom:
                configMapKeyRef:
                  name: mypostgres-config
                  key: PGDATABASE
            - name: PGUSER
              valueFrom:
                configMapKeyRef:
                  name: mypostgres-config
                  key: PGUSER
            - name: PGHOST
              valueFrom:
                configMapKeyRef:
                  name: mypostgres-config
                  key: PGHOST
  replicas: 3
  selector:
    matchLabels:
      app: my-app
      component: backend