apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-local
  labels:
    type: local

spec:
  storageClassName: manual
  capacity:
    storage: 20Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    #path: "C:\\Users\\Gorlist\\Desktop\\Semestr4\\DevOps\\k8spv"
    path: /c/Users/Gorlist/Desktop/Semestr4/DevOps/k8spv # sobie tworzy gdzies tam w VM, nie w prawdziwym systemie